"""init migrations

Revision ID: 807c9b761246
Revises:
Create Date: 2026-07-16 15:17:57.044215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807c9b761246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True, schema='users')
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True, schema='users')
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='admins'
    )
    op.create_index(op.f('ix_admins_permissions_name'), 'permissions', ['name'], unique=True, schema='admins')
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='admins'
    )
    op.create_index(op.f('ix_admins_roles_name'), 'roles', ['name'], unique=True, schema='admins')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='admins'
    )
    op.create_index(op.f('ix_admins_users_email'), 'users', ['email'], unique=True, schema='admins')
    op.create_index(op.f('ix_admins_users_username'), 'users', ['username'], unique=True, schema='admins')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admins.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admins.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='admins'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admins.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admins.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='admins'
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', name='friend_request_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requester_id <> receiver_id', name='ck_friend_requests_distinct_users'),
    sa.PrimaryKeyConstraint('id'),
    schema='social_graph'
    )
    op.create_index('uq_friend_requests_pending_pair', 'friend_requests', [sa.literal_column('least(requester_id, receiver_id)'), sa.literal_column('greatest(requester_id, receiver_id)')], unique=True, schema='social_graph', postgresql_where=sa.text("status = 'pending'"))
    op.create_table('friendships',
    sa.Column('user_low', sa.Uuid(), nullable=False),
    sa.Column('user_high', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_low < user_high', name='ck_friendships_canonical_pair'),
    sa.PrimaryKeyConstraint('user_low', 'user_high'),
    schema='social_graph'
    )
    op.create_index('ix_friendships_user_high', 'friendships', ['user_high'], unique=False, schema='social_graph')
    op.create_index('ix_friendships_user_low', 'friendships', ['user_low'], unique=False, schema='social_graph')
    op.create_table('communities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='community_visibility', native_enum=False), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='communities'
    )
    op.create_index(op.f('ix_communities_communities_name'), 'communities', ['name'], unique=False, schema='communities')
    op.create_index(op.f('ix_communities_communities_owner_id'), 'communities', ['owner_id'], unique=False, schema='communities')
    op.create_table('community_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='communities'
    )
    op.create_index(op.f('ix_communities_community_permissions_name'), 'community_permissions', ['name'], unique=True, schema='communities')
    op.create_table('community_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='communities'
    )
    op.create_index(op.f('ix_communities_community_roles_name'), 'community_roles', ['name'], unique=True, schema='communities')
    op.create_table('community_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['communities.community_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='uq_community_members_user_community'),
    schema='communities'
    )
    op.create_index(op.f('ix_communities_community_members_community_id'), 'community_members', ['community_id'], unique=False, schema='communities')
    op.create_index(op.f('ix_communities_community_members_role_id'), 'community_members', ['role_id'], unique=False, schema='communities')
    op.create_index(op.f('ix_communities_community_members_user_id'), 'community_members', ['user_id'], unique=False, schema='communities')
    op.create_table('community_role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['communities.community_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['communities.community_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='communities'
    )
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'COMMUNITY', name='post_visibility', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_index(op.f('ix_content_posts_author_id'), 'posts', ['author_id'], unique=False, schema='content')
    op.create_index(op.f('ix_content_posts_community_id'), 'posts', ['community_id'], unique=False, schema='content')
    op.create_index(op.f('ix_content_posts_is_deleted'), 'posts', ['is_deleted'], unique=False, schema='content')
    op.create_index(op.f('ix_content_posts_visibility'), 'posts', ['visibility'], unique=False, schema='content')
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index(op.f('ix_notifications_notifications_is_read'), 'notifications', ['is_read'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False, schema='notifications')
    op.create_index(op.f('ix_notifications_notifications_type'), 'notifications', ['type'], unique=False, schema='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_notifications_type'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_recipient_id'), table_name='notifications', schema='notifications')
    op.drop_index(op.f('ix_notifications_notifications_is_read'), table_name='notifications', schema='notifications')
    op.drop_table('notifications', schema='notifications')
    op.drop_index(op.f('ix_content_posts_visibility'), table_name='posts', schema='content')
    op.drop_index(op.f('ix_content_posts_is_deleted'), table_name='posts', schema='content')
    op.drop_index(op.f('ix_content_posts_community_id'), table_name='posts', schema='content')
    op.drop_index(op.f('ix_content_posts_author_id'), table_name='posts', schema='content')
    op.drop_table('posts', schema='content')
    op.drop_table('community_role_permissions', schema='communities')
    op.drop_index(op.f('ix_communities_community_members_user_id'), table_name='community_members', schema='communities')
    op.drop_index(op.f('ix_communities_community_members_role_id'), table_name='community_members', schema='communities')
    op.drop_index(op.f('ix_communities_community_members_community_id'), table_name='community_members', schema='communities')
    op.drop_table('community_members', schema='communities')
    op.drop_index(op.f('ix_communities_community_roles_name'), table_name='community_roles', schema='communities')
    op.drop_table('community_roles', schema='communities')
    op.drop_index(op.f('ix_communities_community_permissions_name'), table_name='community_permissions', schema='communities')
    op.drop_table('community_permissions', schema='communities')
    op.drop_index(op.f('ix_communities_communities_owner_id'), table_name='communities', schema='communities')
    op.drop_index(op.f('ix_communities_communities_name'), table_name='communities', schema='communities')
    op.drop_table('communities', schema='communities')
    op.drop_index('ix_friendships_user_low', table_name='friendships', schema='social_graph')
    op.drop_index('ix_friendships_user_high', table_name='friendships', schema='social_graph')
    op.drop_table('friendships', schema='social_graph')
    op.drop_index('uq_friend_requests_pending_pair', table_name='friend_requests', schema='social_graph', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('friend_requests', schema='social_graph')
    op.drop_table('user_roles', schema='admins')
    op.drop_table('role_permissions', schema='admins')
    op.drop_index(op.f('ix_admins_users_username'), table_name='users', schema='admins')
    op.drop_index(op.f('ix_admins_users_email'), table_name='users', schema='admins')
    op.drop_table('users', schema='admins')
    op.drop_index(op.f('ix_admins_roles_name'), table_name='roles', schema='admins')
    op.drop_table('roles', schema='admins')
    op.drop_index(op.f('ix_admins_permissions_name'), table_name='permissions', schema='admins')
    op.drop_table('permissions', schema='admins')
    op.drop_index(op.f('ix_users_user_profiles_user_id'), table_name='user_profiles', schema='users')
    op.drop_table('user_profiles', schema='users')
    op.drop_index(op.f('ix_users_users_username'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
